spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## payment system key
stripe.secret-key=sk_test_4eC39HqLyjWDarjtT1zdp7dc
stripe.publishable-key=pk_test_TYooMQauvdEDq54NiTphg7jx

## redis cache config
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000